package cafe.logic;

import java.util.Collection;

/**
 * Representation of a special kind of user, who manages cafes in the system.
 * @author David Fuchs
 */
public class Admin extends User {

    private Collection<Cafe> cafes;

    /**
     * Creates a new user, who is an administrator, from information in the database. 
     * ID is automatically generated by the database.
     * 
     * @param id
     * @param email
     * @param name
     * @param surname
     * @param password 
     */
    public Admin(int id,String email,String name,String surname,String password,boolean banned){
        super(id,email,name,surname,password,banned);
    }

    /**
     * Add cafe into the database.
     * @param cafe 
     */
    public void addCafe(Cafe cafe) {
        throw new UnsupportedOperationException();
    }

    /**
     * Ban user from posting and rating cafes.
     * @param user 
     */
    public void ban(User user) {
        throw new UnsupportedOperationException();
    }

}
