package cafe.logic;

/**
 * Representation of a coffee
 * @author David Fuchs
 */
public class Coffee {

    private final int id;

    private double price;

    private String name;

    /**
     * Creates a new coffee from information in the database. ID is automatically 
     * generated by the database.
     * 
     * @param id
     * @param price
     * @param name 
     */
    public Coffee(int id, double price, String name){
        this.id = id;
        this.price = price;
        this.name = name;
    }

    /**
     * Return ID of a kind of coffee.
     * @return 
     */
    public int getID(){
        return id;
    }

    /**
     * Return name of a kind of coffee.
     * @return 
     */
    public String getName(){
        return name;
    }

    /**
     * Converts a coffee into its string representation.
     * @return 
     */
    @Override
    public String toString(){
        return name + ": " + price;
    }
}
