package cafe.logic;

/**
 * Representation of a rating
 * @author David Fuchs
 */
public class Rating {

    private final int id;

    private double stars;

    private User user;

    private Cafe cafe;

    /**
     * Creates a new rating from information in the database. ID is automatically 
     * generated by the database.
     * 
     * @param id
     * @param stars
     * @param user
     * @param cafe 
     */
    public Rating(int id,double stars,User user,Cafe cafe){
        this.id = id;
        this.stars = stars;
        this.user = user;
        this.cafe = cafe;
    }

    /**
     * Get the number of stars given by a user.
     * @return 
     */
    public double getStars(){
        return stars;
    }
}
