package cafe.logic;

import java.util.Date;

/**
 * Representation of a special offer
 * @author David Fuchs
 */
public class SpecialOffer {

    private final int id;

    private Date startDate;

    private Date endDate;

    private String name;

    private String description;

    /**
     * Creates a new special offer from information in the database. ID is automatically 
     * generated by the database.
     * 
     * @param id
     * @param start
     * @param end
     * @param name
     * @param description 
     */
    public SpecialOffer(int id,Date start, Date end, String name, String description){
        this.id = id;
        startDate = start;
        endDate = end;
        this.name = name;
        this.description = description;
    }

    /**
     * Returns name of a special offer.
     * @return 
     */
    public String getName(){
        return name;
    }

    /**
     * Returns ID of a special offer.
     * @return 
     */
    public int getID(){
        return id;
    }

    /**
     * Converts a special offer into its string representation.
     * @return 
     */
    @Override
    public String toString(){
        return name + ": " + startDate + "-" + endDate + "\n" + description;
    }
}
