package cafe.logic;

import java.util.Collection;

/**
 * Representation of a user
 * @author David Fuchs
 */
public class User {
    
    private final int id;

    private String email;

    private String name;

    private String surname;

    private String password;

    private Collection<Post> posts;

    private Collection<Rating> ratings;

    private InformationSystem system;

    /**
     * Creates a new user from information in the database. ID is automatically 
     * generated by the database.
     * 
     * @param id
     * @param email
     * @param name
     * @param surname
     * @param password 
     */
    public User(int id,String email,String name,String surname,String password){
        this.id = id;
        this.email = email;
        this.name = name;
        this.surname = surname;
        this.password = password;
    }

    /**
     * Return user's ID.
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * Return user's name.
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns user's surname.
     * @return the surname
     */
    public String getSurname() {
        return surname;
    }
}
